apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knative-java-build-demo
  namespace: default
spec:
  runLatest:
    configuration:
    build:
      serviceAccountName: g4seek-build-bot
      source:
        git:
          url: https://github.com/g4seek/knative-java-demo.git
          revision: master
      template:
        name: kaniko
        arguments:
          - name: IMAGE
            value: docker.io/g4seek/knative-java-build-demo:latest
      revisionTemplate:
        spec:
          container:
            image: docker.io/g4seek/knative-java-build-demo:latest