apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: knative-java-demo
spec:
  serviceAccountName: g4seek-dockerhub-account
  source:
    git:
      url: https://github.com/g4seek/knative-java-demo.git
      revision: master
  parameters:
    - name: IMAGE
      description: g4seek/knative-java-demo
    - name: DOCKERFILE
      description: ../Dockerfile
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      args:
        - --dockerfile=${DOCKERFILE}
        - --destination=${IMAGE}