apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: knative-java-build-demo
spec:
  serviceAccountName: g4seek-build-bot
  source:
    git:
      url: https://github.com/g4seek/knative-java-demo.git
      revision: master
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/workspace/Dockerfile
        - --destination=docker.io/g4seek/knative-java-demo