apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knative-java-demo
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/g4seek/knative-java-demo
            env:
              - name: TARGET
                value: "Spring Boot Sample v1"
